---
image:
  repository: ghcr.io/frontier-network/corebot
  tag: main
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

service:
  main:
    enabled: false

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 500Mi
    mountPath: /data

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
